FROM python:3.7

ENV PYTHONUNBUFFERED 1

WORKDIR /mirumon-backend

COPY poetry.lock .
COPY pyproject.toml .

RUN pip install poetry && \
    poetry config settings.virtualenvs.create false && \
    poetry install

COPY . .

RUN ./scripts/lint
