version: '3'

services:
  mirumon:
    image: mirumon/mirumon-backend:dev
    container_name: mirumon-backend
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/postgres
      RABBIT_DSN: amqp://rabbitmq:rabbitmq@rabbitmq
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    container_name: mirumon-postgres
    image: postgres:11.5-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/:z
    ports:
      - "5432:5432"
  rabbitmq:
    container_name: mirumon-rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit:z
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
  redis:
    container_name: mirumon-redis
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
